---
title: "Practical Machine Learning"
author: "Shivani Ranjan"
date: "Octpber 5, 2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


## Load library
```{r library, echo=FALSE}

library(caret)
library(knitr)
library(randomForest)
library(rpart)
library(rpart.plot)

```

## Download and loading the Dataset
```{r load data}

# Download the dataset 
trainUrl <- "https://d396qusza40orc.cloudfront.net/predmachlearn/pml-training.csv"
testUrl <- "https://d396qusza40orc.cloudfront.net/predmachlearn/pml-testing.csv"


# Load the dataset into memory
trainingData <- read.csv(url(trainUrl), na.strings = c("NA", "#DIV/0!", ""))
testingData <- read.csv(url(testUrl), na.strings = c("NA", "#DIV/0!", ""))

#
trainingData <- trainingData[, colSums(is.na(trainingData)) == 0]
testingData <- testingData[, colSums(is.na(testingData)) == 0]

# Delete variables that are not related 
trainingData <- trainingData[, -c(1:7)]
testingData <- testingData[, -c(1:7)]

# partioning the training set into two different dataset

traningPartitionData <- createDataPartition(trainingData$classe,  p = 0.7, list = F)
trainingDataSet <- trainingData[traningPartitionData, ]
testingDataSet <- trainingData[-traningPartitionData, ]
dim(trainingData); dim(testingDataSet)

```

## Prediction model 1 - decision tree

```{r feature decision tree}

decisionTreeModel <- rpart(classe ~ ., data = trainingDataSet, method = "class")
decisionTreePrediction <- predict(decisionTreeModel, testingDataSet, type = "class")

# Plot Decision Tree
rpart.plot(decisionTreeModel, main = "Decision Tree", under = T, faclen = 0)

# Using confusion matrix to test results
confusionMatrix(decisionTreePrediction, testingDataSet$classe)

```


## Prediction model 2 - random forest

```{r random forest}

randomForestModel <- randomForest(classe ~. , data = trainingDataSet, method = "class")
randomForestPrediction <- predict(randomForestModel, testingDataSet, type = "class")

confusionMatrix(randomForestPrediction, testingDataSet$classe)

```


## Prediction model 2 - random forest
From the result, it show Random Forest accuracy is higher than Decision tree which is 0.9915  > 0.6644. Therefore, we will use random forest to answer the assignment. 

```{r final prediction}
predictionFinal <- predict(randomForestModel, testingDataSet, type = "class")
#predictionFinal

```
